const banderas = {
    American: "./assets/Usa.png",
    British: "./assets/Bretania.png",
    Canadian: "./assets/Canada.svg",
    Chinese: "./assets/China.png",
    Croatian: "./assets/Croacia.svg",
    Dutch: "./assets/Holanda.svg",
    Egyptian: "./assets/Egipto.svg",
    Filipino: "./assets/Filipinas.svg",
    French: "./assets/Francia.png",
    Greek: "./assets/Grecia.png",
    Indian: "./assets/India.svg",
    Irish: "./assets/Irlanda.svg",
    Italian: "./assets/Italia.png",
    Jamaican: "./assets/Jamaica.png",
    Japanese: "./assets/Japon.png",
    Kenyan: "./assets/Kenia.png",
    Malaysian: "./assets/Malasia.svg",
    Mexican: "./assets/Mexico.png",
    Moroccan: "./assets/Marruecos.png",
    Norwegian: "./assets/Noruega.jpg",
    Polish: "./assets/Polonia.svg",
    Portuguese: "./assets/Portugal.png",
    Russian: "./assets/Rusia.svg",
    Spanish: "./assets/Espania.png",
    Thai: "./assets/Tailandia.png",
    Tunisian: "./assets/tunez.png",
    Turkish: "./assets/Turquia.png",
    Ukrainian: "./assets/Ucrania.png",
    Uruguayan: "./assets/Uruguay.jpg",
    Vietnamese: "./assets/Vietnam.png",
};

export default banderas;
